In [4]:
import torch
from torch import nn

print(torch.backends.mps.is_available())
print(torch.backends.mps.is_built())

True
True


在创建的时候指定设备

In [5]:
device = torch.device('mps' if torch.backends.mps.is_available() else 'cpu')

x = torch.tensor([1, 2, 3], device=device)
x

tensor([1, 2, 3], device='mps:0')

如果对在mps上的tensor进行计算，计算结果也会放在mps上，同时，存储在不同位置中的数据不可以直接进行计算，放在cpu上的数据不能用mps加速

In [6]:
y = x ** 2
y

tensor([1, 4, 9], device='mps:0')

利用mps加速模型计算

In [7]:
net = nn.Linear(3, 1)
list(net.parameters())[0].device

device(type='cpu')

In [8]:
net.to(device)
list(net.parameters())[0].device

device(type='mps', index=0)

同样的，要确保输入的tensor和模型都在同一设备上，否则会报错

In [9]:
x = torch.rand(2, 3).to(device)
net(x)

tensor([[0.1286],
        [0.3135]], device='mps:0', grad_fn=<LinearBackward0>)